# GitHub Actions workflow to build and deploy the weather123 Node.js app to Azure App Service
# Based on https://github.com/Azure/webapps-deploy and https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - weather123

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies, build, and test
        working-directory: ./weatherapp
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./weatherapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4C2F8410A1FB44508BEB88BFF031BCFB }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_39D7CE453AB548E79CBC3456FD08A0D5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3323AE3CE64F4BC5BCF21859E3BCF020 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'weather123'
          slot-name: 'Production'
          package: ./weatherapp
